export const FLASHCARDS = [

  // ── EASY ─────────────────────────────────────────────────────────────────

  {
    id: 1,
    front: 'Revenue',
    back: 'The total amount of money a company earns from selling its products or services — before any costs are subtracted.\n\nAlso called "Net Sales" or "Net Revenue."',
    category: 'Income Statement',
    difficulty: 'easy',
  },
  {
    id: 2,
    front: 'COGS',
    back: 'Cost of Goods Sold — what the company actually paid to buy or produce the products it sold.\n\nFor a clothing store, this is the wholesale price of every item sold.',
    category: 'Income Statement',
    difficulty: 'easy',
  },
  {
    id: 3,
    front: 'Gross Margin',
    back: 'Revenue minus COGS.\n\nThe money left over after paying for the products themselves — before paying for salaries, rent, or marketing.',
    category: 'Income Statement',
    difficulty: 'easy',
  },
  {
    id: 4,
    front: 'Gross Margin %',
    back: 'Gross Margin divided by Revenue, shown as a percentage.\n\n"Out of every dollar of sales, how many cents are left after paying for the product cost?"',
    category: 'Income Statement',
    difficulty: 'easy',
  },
  {
    id: 5,
    front: 'SG&A',
    back: 'Selling, General & Administrative expenses — the overhead costs of running the business.\n\nIncludes employee salaries, store rent, marketing, and utilities. Does NOT include the cost of the products sold.',
    category: 'Income Statement',
    difficulty: 'easy',
  },
  {
    id: 6,
    front: 'Operating Profit',
    back: 'Gross Margin minus SG&A.\n\nThe profit from the company\'s core business operations, before interest payments and taxes.',
    category: 'Income Statement',
    difficulty: 'easy',
  },
  {
    id: 7,
    front: 'Net Profit',
    back: 'The "bottom line" — what remains after ALL expenses, including taxes and interest, have been paid.\n\nThe final profit number a company reports.',
    category: 'Income Statement',
    difficulty: 'easy',
  },
  {
    id: 8,
    front: 'Net Profit Margin %',
    back: 'Net Profit divided by Revenue, as a percentage.\n\nThe share of each sales dollar that becomes final profit after every single expense is paid.',
    category: 'Income Statement',
    difficulty: 'easy',
  },
  {
    id: 9,
    front: 'Inventory',
    back: 'Goods a company has purchased or produced but has not yet sold.\n\nInventory sits on the balance sheet as a current asset until it is sold.',
    category: 'Balance Sheet',
    difficulty: 'easy',
  },
  {
    id: 10,
    front: 'Total Assets',
    back: 'Everything a company owns: cash, inventory, equipment, buildings, and any other resources.\n\nTotal Assets appears on the balance sheet.',
    category: 'Balance Sheet',
    difficulty: 'easy',
  },
  {
    id: 11,
    front: 'ROA',
    back: 'Return on Assets — how much profit a company earns for every dollar of assets it owns.\n\nFormula: Net Profit Margin % × Asset Turnover',
    category: 'Strategic Profit Model',
    difficulty: 'easy',
  },
  {
    id: 12,
    front: 'Asset Turnover',
    back: 'How efficiently a company uses its assets to generate revenue.\n\nFormula: Revenue ÷ Total Assets\n\nA higher number means more revenue is squeezed out of each dollar of assets.',
    category: 'Strategic Profit Model',
    difficulty: 'easy',
  },
  {
    id: 13,
    front: 'Inventory Turnover',
    back: 'How many times a year a company sells through its entire inventory.\n\nFormula: COGS ÷ Inventory\n\nHigher turnover means products are moving off shelves faster.',
    category: 'Strategic Profit Model',
    difficulty: 'easy',
  },
  {
    id: 14,
    front: 'Strategic Profit Model',
    back: 'A framework that breaks ROA into two levers:\n\nROA = Net Profit Margin % × Asset Turnover\n\nCompanies can achieve strong ROA through high margins (luxury) or high turnover (grocery) — or ideally both.',
    category: 'Strategic Profit Model',
    difficulty: 'easy',
  },

  // ── MEDIUM ────────────────────────────────────────────────────────────────

  {
    id: 15,
    front: 'Days in Inventory',
    back: 'How many days, on average, a company holds its inventory before selling it.\n\nFormula: 365 ÷ Inventory Turnover\n\nFewer days = products sell faster. More days = stock sitting on shelves, tying up cash.',
    category: 'Retail Metrics',
    difficulty: 'medium',
  },
  {
    id: 16,
    front: 'Comparable Store Sales',
    back: 'Revenue growth from stores that have been open for at least one year — excludes brand-new store openings.\n\nAlso called "Comp Sales" or "Same-Store Sales." It shows whether existing stores are actually getting busier, without the distortion of new locations.',
    category: 'Retail Metrics',
    difficulty: 'medium',
  },
  {
    id: 17,
    front: 'Sell-Through Rate',
    back: 'The percentage of available inventory that was sold during a period.\n\nFormula: Units Sold ÷ Beginning Inventory × 100\n\nHigh sell-through (80%+) = popular product, good inventory management. Low sell-through = excess stock that may need markdowns.',
    category: 'Retail Metrics',
    difficulty: 'medium',
  },
  {
    id: 18,
    front: 'Average Transaction Value (ATV)',
    back: 'The average dollar amount a customer spends per visit or transaction.\n\nFormula: Total Revenue ÷ Number of Transactions\n\nRetailers increase ATV by upselling, bundling, or cross-selling — getting each customer to add more to their basket.',
    category: 'Retail Metrics',
    difficulty: 'medium',
  },
  {
    id: 19,
    front: 'Sales Per Square Foot',
    back: 'How much revenue a retailer generates for each square foot of store space.\n\nFormula: Annual Revenue ÷ Total Square Footage\n\nA key efficiency metric for physical retail. Apple Stores and Lululemon consistently rank among the highest in the industry.',
    category: 'Retail Metrics',
    difficulty: 'medium',
  },
  {
    id: 20,
    front: 'Markup vs. Gross Margin %',
    back: 'Both describe the gap between cost and price — but they use different denominators.\n\nMarkup = (Price − Cost) ÷ Cost × 100 → based on cost\nGross Margin % = (Price − Cost) ÷ Price × 100 → based on price\n\nA 50% markup is NOT the same as a 50% gross margin.',
    category: 'Retail Metrics',
    difficulty: 'medium',
  },
  {
    id: 21,
    front: 'Working Capital',
    back: 'The money available to fund day-to-day operations.\n\nFormula: Current Assets − Current Liabilities\n\nPositive = company can cover near-term obligations. Negative = a warning sign that short-term debts exceed short-term resources.',
    category: 'Liquidity',
    difficulty: 'medium',
  },
  {
    id: 22,
    front: 'Current Ratio',
    back: 'Measures ability to pay short-term debts using short-term assets.\n\nFormula: Current Assets ÷ Current Liabilities\n\nA ratio above 1.0 means the company has more short-term resources than short-term obligations.',
    category: 'Liquidity',
    difficulty: 'medium',
  },
  {
    id: 23,
    front: 'Accounts Payable',
    back: 'Money a company OWES to its suppliers for goods it has already received but not yet paid for.\n\nA current liability on the balance sheet. Retailers often negotiate favorable payment terms (e.g. "net 60") to hold onto cash longer before paying suppliers.',
    category: 'Balance Sheet',
    difficulty: 'medium',
  },
  {
    id: 24,
    front: 'Accounts Receivable',
    back: 'Money OWED TO a company for goods it has already delivered but not yet been paid for.\n\nA current asset on the balance sheet. For most pure retailers this is near zero, since customers pay at the point of sale.',
    category: 'Balance Sheet',
    difficulty: 'medium',
  },
  {
    id: 25,
    front: 'CAGR',
    back: 'Compound Annual Growth Rate — the steady annual growth rate that would take a starting value to an ending value over a number of years.\n\nUsed to compare how fast different companies or metrics have grown over time, removing year-to-year noise.',
    category: 'Advanced Financials',
    difficulty: 'medium',
  },
  {
    id: 26,
    front: 'EBITDA',
    back: 'Earnings Before Interest, Taxes, Depreciation, and Amortization.\n\nMeasures core operating profitability by stripping out financing decisions (interest), tax rules, and accounting choices (depreciation). Often used to compare companies with different debt levels.',
    category: 'Advanced Financials',
    difficulty: 'medium',
  },
  {
    id: 27,
    front: 'High Margin / Low Turnover vs. Low Margin / High Turnover',
    back: 'Two opposite strategies that can achieve similar ROA:\n\nHigh margin / low turnover → luxury & department stores (e.g. Nordstrom): charge more per item, sell fewer\n\nLow margin / high turnover → grocery & warehouse clubs (e.g. Costco, Kroger): tiny profit per item, but sell enormous volumes',
    category: 'Strategic Profit Model',
    difficulty: 'medium',
  },

  // ── HARD ─────────────────────────────────────────────────────────────────

  {
    id: 28,
    front: 'GMROI',
    back: 'Gross Margin Return on Inventory — how many dollars of gross margin a retailer earns for every dollar invested in inventory.\n\nFormula: Gross Margin ÷ Average Inventory Cost\n\nA GMROI above $1.00 means the inventory is generating more margin than it cost to hold.',
    category: 'Retail Metrics',
    difficulty: 'hard',
  },
  {
    id: 29,
    front: 'Shrinkage',
    back: 'The loss of inventory through theft (shoplifting or employee theft), administrative errors, or supplier fraud — without a corresponding sale.\n\nShrinkage directly hurts Gross Margin: the cost of lost goods hits COGS but generates no Revenue.',
    category: 'Retail Metrics',
    difficulty: 'hard',
  },
  {
    id: 30,
    front: 'Quick Ratio',
    back: 'A stricter liquidity measure that excludes inventory, since inventory can\'t always be converted to cash quickly in a crisis.\n\nFormula: (Current Assets − Inventory) ÷ Current Liabilities\n\nAlso called the "Acid-Test Ratio." Especially important for retailers who carry a lot of slow-moving stock.',
    category: 'Liquidity',
    difficulty: 'hard',
  },
  {
    id: 31,
    front: 'Debt-to-Equity Ratio',
    back: 'Shows how much a company relies on borrowed money versus shareholders\' own money.\n\nFormula: Total Debt ÷ Shareholders\' Equity\n\nA high ratio signals heavy reliance on debt, which increases financial risk — especially dangerous when sales decline.',
    category: 'Leverage',
    difficulty: 'hard',
  },
  {
    id: 32,
    front: 'Interest Coverage Ratio',
    back: 'How easily a company can pay the interest on its debt from its operating earnings.\n\nFormula: Operating Profit ÷ Interest Expense\n\nA ratio below 1.5 is considered risky — the company barely earns enough to cover its interest payments, let alone repay principal.',
    category: 'Leverage',
    difficulty: 'hard',
  },
  {
    id: 33,
    front: 'Operating Leverage',
    back: 'The degree to which a company\'s cost structure is fixed versus variable.\n\nHigh operating leverage = large fixed costs (rent, salaries). When sales rise, profit jumps fast — but when sales fall, losses mount just as fast.\n\nLow operating leverage = mostly variable costs that scale with sales.',
    category: 'Advanced Financials',
    difficulty: 'hard',
  },
  {
    id: 34,
    front: 'Free Cash Flow',
    back: 'The actual cash a company generates after paying for capital expenditures.\n\nFormula: Operating Cash Flow − Capital Expenditures\n\nA company can be profitable on paper but still have negative free cash flow if it\'s spending heavily on store expansions or infrastructure.',
    category: 'Advanced Financials',
    difficulty: 'hard',
  },
  {
    id: 35,
    front: 'Capital Expenditures (CapEx)',
    back: 'Money spent on long-term physical assets — new stores, warehouses, technology systems, or equipment.\n\nCapEx appears on the cash flow statement, not the income statement. Instead of being expensed immediately, it is depreciated gradually over the life of the asset.',
    category: 'Advanced Financials',
    difficulty: 'hard',
  },

  // ── EASY – new additions ──────────────────────────────────────────────────

  {
    id: 36,
    front: 'Current Assets',
    back: 'Assets a company expects to convert into cash within one year.\n\nIncludes: cash, accounts receivable, and inventory.\n\nCurrent Assets appear at the top of the balance sheet and are the most liquid things a company owns.',
    category: 'Balance Sheet',
    difficulty: 'easy',
  },
  {
    id: 37,
    front: 'Current Liabilities',
    back: 'Debts and obligations a company must pay within one year.\n\nIncludes: accounts payable, short-term loans, and accrued expenses.\n\nIf Current Liabilities are larger than Current Assets, the company may struggle to pay its bills.',
    category: 'Balance Sheet',
    difficulty: 'easy',
  },
  {
    id: 38,
    front: 'Shareholders\' Equity',
    back: 'The portion of a company\'s assets that belongs to its owners after all debts are paid.\n\nFormula: Total Assets − Total Liabilities\n\nAlso called "net worth" or "book value." A growing equity balance generally signals a healthy, profitable company.',
    category: 'Balance Sheet',
    difficulty: 'easy',
  },
  {
    id: 39,
    front: 'Foot Traffic',
    back: 'The number of people who physically enter a store during a given period.\n\nHigher foot traffic gives a store more chances to make a sale. Retailers track foot traffic alongside Conversion Rate to understand how well they turn visitors into buyers.',
    category: 'Retail Metrics',
    difficulty: 'easy',
  },
  {
    id: 40,
    front: 'Conversion Rate',
    back: 'The percentage of store visitors who actually make a purchase.\n\nFormula: Number of Transactions ÷ Foot Traffic × 100\n\nA low conversion rate means people are browsing but not buying — often a sign of pricing, product, or service issues.',
    category: 'Retail Metrics',
    difficulty: 'easy',
  },
  {
    id: 41,
    front: 'Markdown',
    back: 'A permanent reduction in the selling price of a product — usually to clear out slow-moving or end-of-season inventory.\n\nMarkdowns directly reduce Gross Margin because the product sells for less than originally planned.',
    category: 'Retail Metrics',
    difficulty: 'easy',
  },
  {
    id: 42,
    front: 'Fixed Costs',
    back: 'Expenses that stay the same regardless of how much a company sells.\n\nExamples: store rent, salaried employees, insurance.\n\nFixed costs must be paid even if sales drop to zero, which is why they create financial risk during slow periods.',
    category: 'Advanced Financials',
    difficulty: 'easy',
  },
  {
    id: 43,
    front: 'Variable Costs',
    back: 'Expenses that rise and fall directly with sales volume.\n\nExamples: cost of goods sold, packaging, shipping, hourly staff wages.\n\nUnlike fixed costs, variable costs only occur when a sale is made — so they naturally shrink if sales slow down.',
    category: 'Advanced Financials',
    difficulty: 'easy',
  },

  // ── MEDIUM – new additions ────────────────────────────────────────────────

  {
    id: 44,
    front: 'Units Per Transaction (UPT)',
    back: 'The average number of items a customer buys in a single transaction.\n\nFormula: Total Units Sold ÷ Number of Transactions\n\nRetailers increase UPT through product bundling, "buy 2 get 1" promotions, and suggestive selling by store associates.',
    category: 'Retail Metrics',
    difficulty: 'medium',
  },
  {
    id: 45,
    front: 'Open-to-Buy (OTB)',
    back: 'A budgeting tool that tells a buyer how much inventory they are allowed to purchase in a given period without overstocking.\n\nFormula: Planned Sales + Planned End Inventory − Beginning Inventory\n\nOTB keeps inventory investment aligned with sales forecasts.',
    category: 'Retail Metrics',
    difficulty: 'medium',
  },
  {
    id: 46,
    front: 'Return Rate',
    back: 'The percentage of sold items that customers bring back for a refund or exchange.\n\nFormula: Units Returned ÷ Units Sold × 100\n\nHigh return rates hurt profitability — returned goods must be re-processed or marked down, and the original sale revenue is lost.',
    category: 'Retail Metrics',
    difficulty: 'medium',
  },
  {
    id: 47,
    front: 'Return on Equity (ROE)',
    back: 'How much profit a company generates for every dollar of shareholders\' equity.\n\nFormula: Net Profit ÷ Shareholders\' Equity\n\nROE measures how effectively management is using investors\' money. A higher ROE is generally better.',
    category: 'Strategic Profit Model',
    difficulty: 'medium',
  },
  {
    id: 48,
    front: 'Financial Leverage',
    back: 'Using borrowed money (debt) to amplify the potential return on investment.\n\nIf a company finances growth with debt and earns more than the interest cost, leverage boosts ROE. But if sales fall, the fixed interest payments become a heavy burden.',
    category: 'Leverage',
    difficulty: 'medium',
  },
  {
    id: 49,
    front: 'Long-term Debt',
    back: 'Loans and financial obligations that are due more than one year from now.\n\nExamples: corporate bonds, mortgages on store properties, multi-year bank loans.\n\nLong-term debt appears on the balance sheet and generates ongoing interest expense on the income statement.',
    category: 'Balance Sheet',
    difficulty: 'medium',
  },
  {
    id: 50,
    front: 'Depreciation',
    back: 'The gradual expensing of a long-term asset\'s cost over its useful life.\n\nExample: a $1,000,000 warehouse depreciated over 10 years = $100,000 expense per year.\n\nDepreciation is a non-cash expense — it reduces reported profit but does not involve any cash leaving the company.',
    category: 'Advanced Financials',
    difficulty: 'medium',
  },
  {
    id: 51,
    front: 'Break-even Point',
    back: 'The level of sales at which total revenue exactly equals total costs — the company makes neither a profit nor a loss.\n\nFormula: Fixed Costs ÷ Gross Margin %\n\nKnowing the break-even point helps managers understand how much they must sell before the business becomes profitable.',
    category: 'Advanced Financials',
    difficulty: 'medium',
  },
  {
    id: 52,
    front: 'Cash Conversion Cycle',
    back: 'How many days it takes a company to convert its inventory investment back into cash from sales.\n\nFormula: Days in Inventory + Days Sales Outstanding − Days Payable Outstanding\n\nA shorter cycle means cash comes back faster — critical for retailers managing tight working capital.',
    category: 'Liquidity',
    difficulty: 'medium',
  },

  // ── HARD – new additions ─────────────────────────────────────────────────

  {
    id: 53,
    front: 'Contribution Margin',
    back: 'Revenue minus variable costs only — the amount each unit sold "contributes" toward covering fixed costs and generating profit.\n\nFormula: Revenue − Variable Costs\n\nUnlike Gross Margin, Contribution Margin separates fixed and variable costs to show the true profitability of each additional sale.',
    category: 'Income Statement',
    difficulty: 'hard',
  },
  {
    id: 54,
    front: 'Goodwill',
    back: 'An intangible asset recorded when a company pays more than the book value of another business it acquires.\n\nIt represents the value of things that can\'t easily be measured — brand reputation, customer loyalty, and skilled employees.\n\nGoodwill must be tested annually for "impairment" (loss of value).',
    category: 'Balance Sheet',
    difficulty: 'hard',
  },
  {
    id: 55,
    front: 'Retained Earnings',
    back: 'The cumulative total of all net profits a company has earned and NOT paid out as dividends — kept inside the business to fund growth.\n\nRetained Earnings grow every year the company is profitable and shrink when dividends are paid or losses occur.',
    category: 'Balance Sheet',
    difficulty: 'hard',
  },
  {
    id: 56,
    front: 'Stock-to-Sales Ratio',
    back: 'Compares how much inventory a retailer holds relative to how much it sells in a period.\n\nFormula: Beginning-of-Month Inventory ÷ Sales for the Month\n\nA high ratio means too much inventory on hand. Buyers use this to decide whether to slow down new orders or push markdowns.',
    category: 'Retail Metrics',
    difficulty: 'hard',
  },
  {
    id: 57,
    front: 'Return on Invested Capital (ROIC)',
    back: 'Measures how efficiently a company generates profit from all the capital invested in the business — both debt and equity.\n\nFormula: Net Operating Profit After Tax ÷ Invested Capital\n\nROIC above the company\'s cost of capital means the business is creating value; below it means value is being destroyed.',
    category: 'Advanced Financials',
    difficulty: 'hard',
  },
  {
    id: 58,
    front: 'Weighted Average Cost of Capital (WACC)',
    back: 'The average rate a company must earn on its investments to satisfy both its debt holders and equity investors.\n\nIt blends the cost of debt and cost of equity, weighted by how much of each the company uses.\n\nWACC is the minimum return threshold — any project earning less than WACC destroys shareholder value.',
    category: 'Advanced Financials',
    difficulty: 'hard',
  },
  {
    id: 59,
    front: 'Leverage Buyout (LBO)',
    back: 'The acquisition of a company using a large amount of borrowed money, with the acquired company\'s assets and cash flows used as collateral.\n\nPrivate equity firms use LBOs to buy retailers. The heavy debt load means the company must generate strong, consistent cash flow — or risk bankruptcy.',
    category: 'Leverage',
    difficulty: 'hard',
  },
  {
    id: 60,
    front: 'DuPont Analysis',
    back: 'A framework that breaks ROE into three components to diagnose where performance comes from:\n\nROE = Net Profit Margin % × Asset Turnover × Financial Leverage\n\nIt reveals whether a company\'s strong ROE is driven by efficient operations, efficient asset use, or simply taking on more debt.',
    category: 'Strategic Profit Model',
    difficulty: 'hard',
  },
];
